### ISSUE TITLE
宏定义  需要屏蔽 否则程序崩溃

### ISSUE THREAD

**Issue by summerHearts** [ming1016/SMCheckProject#3]

**Comment by ming1016** [comment]
宏定义现在是屏蔽的

**Comment by summerHearts** [comment]
<img width="755" alt="2016-11-03 12 49 24" src="https://cloud.githubusercontent.com/assets/10678821/19956163/0da744c2-a1c4-11e6-9af9-848f5b4781b6.png">

#define RGBA(r, g, b,a) [UIColor colorWithRed:r / 255.0f green:g / 255.0f blue:b / 255.0f alpha:a]

我觉得是这句话没正确处理

**Comment by ming1016** [comment]
是#define END_TAG @]\ 这句定义的问题。

**Comment by ming1016** [comment]
已经修复

**Comment by summerHearts** [comment]
谢谢
发自网易邮箱大师
在2016年11月03日 14:59，戴铭 写道:

已经修复
