### ISSUE TITLE
误伤的好多啊。。

### ISSUE THREAD

**Issue by DreamBuddy** [ming1016/SMCheckProject#4]
大概 是 可以加入一个 对单独文件 清理的功能吗？ 一键清理 有些怕..

**Comment by ming1016** [comment]
@DreamBuddy 将需要清理的放到一个文件夹里就可以针对指定的文件进行清理。在清理前会在列表中列出无用方法，可以手动清理。如果是一键清理也是注释掉，也能够手动恢复。
