### ISSUE TITLE
使用utf8编码解析错误

### ISSUE THREAD

**Issue by canyonliu** [ming1016/SMCheckProject#6]
![image](https://cloud.githubusercontent.com/assets/8326041/21759899/eea361ac-d682-11e6-886f-05c9e36c27ee.png)
![image](https://cloud.githubusercontent.com/assets/8326041/21759926/247175bc-d683-11e6-9198-ab2282dc10c6.png)

**Comment by ming1016** [comment]
目前还没有处理其它编码
